/*
 * This file was generated by the Gradle 'init' task.
 */

group = "io.mintybayleaf"
version = "1.0"

plugins {
    kotlin("jvm") version "1.8.0"    
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies { 
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
}

kotlin {
    jvmToolchain(17)
}

tasks.register<Jar>("thiccjar") {
 dependsOn.addAll(listOf("compileJava", "compileKotlin", "processResources")) 
    this.archiveFileName.set("thiccmintboy.jar")
    this.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    this.manifest { attributes(mapOf("Main-Class" to application.mainClass)) }
    val sourcesMain = sourceSets.main.get()
    val contents = configurations.runtimeClasspath.get()
        .map { if (it.isDirectory) it else zipTree(it) } +
            sourcesMain.output
    this.from(contents)
}

tasks {
    build {
        dependsOn("thiccjar")
    }
}

application {
    // Define the main class for the application.
    mainClass.set("io.mintybayleaf.mintboy.AppKt")
}
